# Site settings
title: Lawrence Pan
email: lawrencefeipan@gmail.com
name: 'lpan.io'
description: "Lawrence Pan's profile and blog"
baseurl: ""
url: "http://lpan.io"

twitter_username: l_pan_
github_username: lpan
linkedin_username: lawrence-pan

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

# Build settings
markdown: kramdown

permalink: /:title/
resume_url: "https://s3.amazonaws.com/lpan-resume/resume.pdf"
