# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: ./blog.sh
email: suyashgargsfam@gmail.com
tagline: ferbncode
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ferbncode.github.io" # the base hostname & protocol for your site, e.g. http://example.com
exclude:
  - Gemfile
  - Gemfile.lock

github:
  url:               ""
author:
  name:              "Suyash Garg"
  email:             "suyashgargsfam@gmail.com"
  twitter:           "ferbncode"
  github:            "ferbncode"
  linkedin:          "gargsuyash"
paginate:            5

resume_url: "https://drive.google.com/file/d/1AkwhFtojWrzScpVC5K-UBQU9AvZoAIDc/view?usp=sharing"

# # Collections
collections:
  reads:
    output: true
  talks:
    output: true
  selftalks:
    output: true
  piano:
    output: true
  conv:
    output: true
  


# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate, jekyll-sitemap, jekyll-feed]


timezone: Europe/Berlin
