# Site settings
title: Suyash Garg
email: suyashgargsfam@gmail.com
name: 'ferbnocde'
description: ":help 42 && :wq"
baseurl: ""
url: "ferbncode.github.io"

twitter_username: ferbncode
github_username: ferbncode
linkedin_username: gargsuyash

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

# Build settings
markdown: kramdown

permalink: /:title/
resume_url: "https://drive.google.com/file/d/0B4wvTlfykBv_YXJ4a25wWFhNY1E/view?usp=sharing"
